# Python Notları

### Map Fonksiyonu

In [9]:
l=[1,2,3,4,5,6,7,8,9,10]
def func(x):
    return x**x
newlist=[]

for x in l:
    newlist.append(func(x))
    
print(newlist)

[1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000]


Map fonksiyonu parametre olarak bir fonksiyon ve liste alır. Fonksiyonu listenin her bir elemanı için çalıştırır. Yukarıdaki kodu tek bir satırla ifade etmemize yarar.

In [1]:
l=[1,2,3,4,5,6,7,8,9,10]
def func(x):
    return x**x
print(type(map(func,l)))

<class 'map'>


In [3]:
print(list(map(func,l)))

[1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000]


Kodlarda bu işlemi çoğunlukla böyle yazılmaktadır [(ifade) for x in list]. Bu yapı oldukça kullanışlı yazılım kolaylığı sunuyor.

In [6]:
print([func(x) for x in l])

[1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000]


for ifadesi bir if koşulu ile de desteklenebilmektedir.

In [7]:
print([func(x) for x in l if x%2==0])

[4, 256, 46656, 16777216, 10000000000]


### Filter Fonksiyonu 

Filter fonksiyonu parametre olaran bir fonksiyon ve liste alır. Listenin her elemanı için bu fonksiyonun ürettiği boolean değere göre listeyi yeniden oluşturur.

In [10]:
def add7(x):
    return x+7

def isOdd(x):
    return x%2 != 0

a=[1,2,3,4,5,6,7,8,9,10]

b=list(filter(isOdd,a))
print(a)
print(b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 3, 5, 7, 9]


Pekiştirmek için işin içine map fonksiyonunu da dahil edelim.

In [11]:
c = list(map(add7,b))
print(c)

[8, 10, 12, 14, 16]


Daha kısa bir gösterimle

In [16]:
c = [add7(x) for x in filter(isOdd,a)]
print(c)

[8, 10, 12, 14, 16]


### Numpy Array için Boolean İfadesi

Filtre metoduna ek olarak numpy'da matris işlemleri yaparken değerleri boolean ifade sonucuna göre değiştirmek için aşağıdaki ifade kullanılabilir.

In [28]:
import numpy as np

npA = np.asarray(a)
print(npA)
print(type(npA))



[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [31]:
npA = np.asarray(a)
npA[npA>5]=0
print(npA)

npA = np.asarray(a)
npA=npA[(npA>2) & (npA<8)]
print(npA)

[1 2 3 4 5 0 0 0 0 0]
[3 4 5 6 7]


### Lambda Fonksiyonu

Lambda ifadeleri fonksiyonlarımızı oluşturmak için Pythonda bulunan pratik bir yöntemdir ve gerektiği yerlerde bu ifadeleri kullanabiliriz.

In [34]:
def func(x):
    return x+5
    
print(func(2))

7


In [35]:
func = lambda x:x+5
print(func(2))

7


Lambda birden fazla değişken ile de kullanılabilir. Aynı zamanda opsiyonel parametreler ile de kullanılabilir ve fonksiyon içinde tanımlanabilir

In [36]:
func2 = lambda x,y:x+y
print(func2(3,5))

8


In [41]:
func3 = lambda a,b=1: (a+1)*((b+1)**2)
print(func3(2,1))   #3*4

12


In [58]:
def fonk(x):
    def fonk2(y):
        return y+2
    return fonk2(x)

print(fonk(2))

def fonk(x):
    fonk2 = lambda x:x+2
    return fonk2(x)
print(fonk(2))

4
4


Lambda filter ve map fonksiyonları ile kullanışlıdır.

In [52]:
a=[1,2,3,4,5,6,7,8,9,10]
print(list(map(lambda x:x**2, a)))
print(list(filter(lambda x:x%2==0, a)))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[2, 4, 6, 8, 10]


Lambda geriye bir fonksiyon nesnesi döndürmektedir. Bu fonksiyonun return ile döndürülen parametre ile karıştırılmamalıdır.

In [53]:
print([lambda x:x**2 for i in a]) # Lambda fonksiyon döndürdüğü için fonksiyon nesnesi bastırılmış olur

[<function <listcomp>.<lambda> at 0x0000015BDD18A840>, <function <listcomp>.<lambda> at 0x0000015BDD18A598>, <function <listcomp>.<lambda> at 0x0000015BDD18A620>, <function <listcomp>.<lambda> at 0x0000015BDD18A7B8>, <function <listcomp>.<lambda> at 0x0000015BDD18A0D0>, <function <listcomp>.<lambda> at 0x0000015BDD18A510>, <function <listcomp>.<lambda> at 0x0000015BDD18A400>, <function <listcomp>.<lambda> at 0x0000015BDC5052F0>, <function <listcomp>.<lambda> at 0x0000015BDC505A60>, <function <listcomp>.<lambda> at 0x0000015BDC505E18>]


In [56]:
print([x**2 for x in a]) # Kullanılması gereken notasyon bu şekildedir

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


### *args ve **kwargs

Fonksiyonlarımızı tanımlarken, bazı durumlarda pratikte sınırsız (aslında 256 parametre) parametre vermek isteyebiliriz. Bu durumlarda bazı özel işaretleri parametremizden önce kullanmamız gerekir.

*args
Sınırsız sayıda parametreli fonksiyon oluşturmak için parametremizin önüne tek yıldız (*) koyabiliriz.

In [15]:
def rakamlari_goster(*rakamlar):
    print(rakamlar)
 
rakamlari_goster(1,2,3,4)
rakamlari_goster(15,'burak')

def fonksiyon(*args):
 
    for i in args:
        print(i)
 
liste = [10, 2.5, 'burak', True]
 
fonksiyon(liste)
 

(1, 2, 3, 4)
(15, 'burak')
[10, 2.5, 'burak', True]


**kwargs
Çift yıldızlı (**) parametrelerin tek yıldızlı (*) parametrelerden en önemli farkı, fonksiyonu çağırırken anahtar değer ilişkisiyle çağırabilmemizdir. Burada, fonksiyon parametresinden önce çift yıldız(**) kullandığımız için sonucumuz sözlük (dictionary) olarak döner.

In [16]:
def fonksiyon1(**parametre):
    print(parametre)
 
fonksiyon1(değer1='Burak', deger2 =20)
fonksiyon1(değer1='Burak', deger2 =20,deger3 = True,deger4= 15.2)

{'değer1': 'Burak', 'deger2': 20}
{'değer1': 'Burak', 'deger2': 20, 'deger3': True, 'deger4': 15.2}


In [17]:
def fonksiyon(*args,**kwargs):
    for i in args:
        print(i)
    for k,v in kwargs.items():
        print('anahtar: ',k,'Degerimiz: ',v)
 
fonksiyon(1,2,3,'args' , deger = 'kwargs')

1
2
3
args
anahtar:  deger Degerimiz:  kwargs


### Decorators

Python'da fonksiyonlar da birer obje oldukları için fonksiyon içerisinde geri döndürülebilir.

In [1]:
def func(string):
    def wrapper():
        print("Hey")
        print(string)
        print("End")
    return wrapper

x=func("Hello")

In [2]:
print(x)

<function func.<locals>.wrapper at 0x000002280808F2F0>


In [3]:
x()

Hey
Hello
End


In [4]:
def func(f):
    def wrapper():
        print("Hey")
        f()
        print("End")
    return wrapper

def func2():
    print("I am func2")
    
x=func(func2)

In [5]:
print(x)
x()

<function func.<locals>.wrapper at 0x000002280808F8C8>
Hey
I am func2
End


Decorators yukarıdaki notasyonu kolaylaştıran bir yapıdır. 

In [9]:
def func(f):
    def My_wrapper():
        print("Hey")
        f()
        print("End")
    return My_wrapper

@func
def func2():
    print("Hi I'am func2")
    
func2()

Hey
Hi I'am func2
End


In [11]:
@test
def func3():
    print("Hi I'am func3")
    
func3()

NameError: name 'test' is not defined

farklı girdi sayısına sahip fonksiyonları çalıştırmak için decorator fonksyionda * args ** kwargs yapısı kullanılır

In [20]:
def myFunc(f):
    def inner_func(*args, **kwargs):
        print("started")
        rv = f(*args, **kwargs)
        print("Ended")
        return rv
    return inner_func

@myFunc
def func2(x,y):
    print(x)
    return y

@myFunc
def func3(x,y):
    print(x)
    return y

val = func2(3,4)
print(val)

val = func3(5,6)
print(val)


started
3
Ended
4
started
5
Ended
6


Decorators işlevsel kullanıma örnek olarak aşağıdaki kod parçası incelenebilir. Timer'a gönderilen fonksiyonun işlenme süresini ekrana yazdırmaktadır.

In [24]:
import time

def timer(f):
    def wrapper(*args, **kwargs):
        s=time.time()
        rv = f(*args, **kwargs)
        total_time= time.time() - s
        print("Time: ",total_time)
        return rv
    return wrapper

@timer
def delay(x):
    for i in range(0,x):
        pass
    
@timer
def sleep(x):
    time.sleep(x)
    
delay(100000)
delay(100000000)
sleep(2)

Time:  0.0020101070404052734
Time:  1.6106765270233154
Time:  2.0006182193756104


### Generators

Generatörler de iteratörler gibi __next__() fonksiyonuna sahiptir ve bu sayede iterasyon işlemine tabi tutulabilirler.
Generatörlerin iteratörlerden farkı ise lazy evaluation yapmalarıdır. Bir objeyi itere etmek istediğinizde liste elemanları ile birlikte itere edilmeye hazırdır ve sırası ile bu elemanları çağırarak işlem yapmaya başlarsınız. Generatörlerde elinizde iterasyona tabi tutacağınız elemanlar halihazırda mevcut değildir, siz bir sonrakini çağırdığınız zaman üretilir ve size sunulur. Bu ne işimize yarayacak derseniz, yapacağınız işlem için bir listenin tüm elemanlarına ihtiyacınız yoksa veya ne kadarını kullanacağınızı bilmiyorsanız boşu boşuna listenin hepsini oluşturup memory’yi şişirmek yerine generatör kullanarak ihtiyaç duydukça/çağırdıkça elemanların üretilmesini sağlayıp fazla memory kullanımının önüne geçebilirsiniz.

kaynak: https://medium.com/python-yaz-lar/python-generator-ve-i-teratorler-a53e59f7c5b1

In [25]:
# x = [i**2 for i in range(100000000000)]
#Bu kod çalıştığında memory hatası alırız çünkü 100000000000 tane sayının karesini depolayacak memory olmadığından python bize
#böyle bir hata döndürür

Generatorlar iterasyon işlemine tutulabilirler ama yanlızca ilgili index ile işlem yaparlar. Diğer değerler herhangi bir şekilde depolanmaz bu da bellek kullanımını oldukça azaltan faktördür

In [26]:
def gen(n):
    for i  in range(n):
        yield i**2
        
g = gen(10) #Şişme olmaması için az sayıda değer bastırıyorum ama sonsuz değer girsek de bellek taşması meydana gelmez!

for i in g:
    print(i)

0
1
4
9
16
25
36
49
64
81


In [28]:
g = gen(1000)
print(next(g))
print(next(g))
print(next(g))
print(next(g))

0
1
4
9


In [29]:
def gen():
    yield 10
    yield 100
    yield 1000
    yield 10000
    
g = gen()
print(next(g))
print(next(g))
print(next(g))
print(next(g))

10
100
1000
10000


Generatorslar ile kazanılan bellek durumunu kontrol edelim

In [32]:
import sys

x = [i**2 for i in range(10000)] 
g = (i**2 for i in range(10000)) #Generator kısa gösterimi

print(type(x))
print(type(g))

print(sys.getsizeof(x))
print(sys.getsizeof(g))

<class 'list'>
<class 'generator'>
87624
120


Notların bir çoğu https://www.youtube.com/c/TechWithTim Tech with Tim youtube kanalındaki intermediate expert python oynatma listesinden alınmıştır. Daha fazla bilgi için bu kanalı ziyaret etmenizi tavsiye ederim